### ISSUE TITLE
Where to put the config.txt

### ISSUE THREAD

**Issue by casidiablo** [paperdink/timcal#2]
This project lacks documentation on how to properly provide a config.txt, and its expected format (by looking at the code it seems like JSON).

I tried pushing a dummy config.txt file to the SD card root, but it does not work.

**Comment by rgujju** [comment]
Hello,
You don't actually need to upload a JSON file manually. When you upload this specific sketch the device will start a hotspot to which you can connect and enter your configuration details.

**Comment by casidiablo** [comment]
Ahh wow, that's quite interesting. I will give it a try.

**Comment by sharkoz** [comment]
But is there a way to force the parameters from a file or from the sketch ?
As a matter of fact it is not very practical in my use case to enter the weather api key from the ui of the AP for example. I would rather set it once and for all from a file, a .h or the ino sketch directly for example.

**Comment by sharkoz** [comment]
I found that you can set the config.txt file in the /data folder with the following json : 
`{"city":"","country":"","todoist_token":"","openweather_appkey":"","timezone":"","config_done":1}`

But I have still not found the correct way to configure the timezones

**Comment by rgujju** [comment]
Hi @sharkoz 
We have added a new example [Timcal2](https://github.com/paperdink/timcal2) where you can configure using config.h

**Comment by casidiablo** [comment]
I also have no idea how to properly configure the timezone.

**Comment by sharkoz** [comment]
I found that page to resolve the full TZ strings for different time zones :
[https://leo.leung.xyz/wiki/Timezone](https://leo.leung.xyz/wiki/Timezone)

I replaced the full string `time_zone_string` directly in `date_time.cpp`, for example :
`String time_zone_string = "CET-1CEST,M3.5.0,M10.5.0/3";`
